### ISSUE TITLE
Repo status?

### ISSUE THREAD

**Issue by tnir** [duckinator/bundler-viz#1]
This repo seems at very top in search engine results: https://www.google.com/search?q=bundler+viz . Do you have any plan on this  repo? 👁️ 

As you are one of `@rubygems` as well as `@rubytogether`, you could show the current status by updating status of this repo. Thank in advance.

### Resources
- https://github.com/rubygems/rubygems/issues/3333#issuecomment-753869107

**Comment by tnir** [comment]
@duckinator What do you think?

**Comment by duckinator** [comment]
Hey, yeah I'm one of the RubyGems maintainers + work for Ruby Together.

This has been superseded by https://github.com/rubygems/bundler-graph , and this repo is completely irrelevant.

**Comment by duckinator** [comment]
I updated it so that there's nothing but a README pointing at bundler-graph, and the description also points there. I'm going to close this issue and then archive the repo.

![image](https://user-images.githubusercontent.com/39698/180490600-b20ebd92-7772-4416-9a3d-5dce204f2859.png)
